package com.model;

import java.util.List;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{

	private Integer catelogId;
	private String catelogName;
	private String catelogDel;
	
	private List xiaoleibieList;
	
	public String getCatelogDel()
	{
		return catelogDel;
	}
	public void setCatelogDel(String catelogDel)
	{
		this.catelogDel = catelogDel;
	}
	public Integer getCatelogId()
	{
		return catelogId;
	}
	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}
	public String getCatelogName()
	{
		return catelogName;
	}
	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}
	public List getXiaoleibieList()
	{
		return xiaoleibieList;
	}
	public void setXiaoleibieList(List xiaoleibieList)
	{
		this.xiaoleibieList = xiaoleibieList;
	}

}