package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	private Integer goodsId;
	private Integer xiaoleibieId;
	private String goodsName;
	private String goodsZuozhe;

	private String goodsMulu;
	private String goodsPic;
	private Integer goodsShichangjia;
	private Integer goodsTejia;

	private String fabushi;
	private String goodsDel;
	
	
	public String getFabushi()
	{
		return fabushi;
	}
	public void setFabushi(String fabushi)
	{
		this.fabushi = fabushi;
	}
	public String getGoodsDel()
	{
		return goodsDel;
	}
	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}
	public Integer getGoodsId()
	{
		return goodsId;
	}
	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}
	public String getGoodsMulu()
	{
		return goodsMulu;
	}
	public void setGoodsMulu(String goodsMulu)
	{
		this.goodsMulu = goodsMulu;
	}
	public String getGoodsName()
	{
		return goodsName;
	}
	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}
	public String getGoodsPic()
	{
		return goodsPic;
	}
	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}
	public Integer getGoodsShichangjia()
	{
		return goodsShichangjia;
	}
	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}
	public Integer getGoodsTejia()
	{
		return goodsTejia;
	}
	public void setGoodsTejia(Integer goodsTejia)
	{
		this.goodsTejia = goodsTejia;
	}
	public String getGoodsZuozhe()
	{
		return goodsZuozhe;
	}
	public void setGoodsZuozhe(String goodsZuozhe)
	{
		this.goodsZuozhe = goodsZuozhe;
	}
	public Integer getXiaoleibieId()
	{
		return xiaoleibieId;
	}
	public void setXiaoleibieId(Integer xiaoleibieId)
	{
		this.xiaoleibieId = xiaoleibieId;
	}

}