package com.model;

/**
 * TPinglun generated by MyEclipse Persistence Tools
 */

public class TPinglun implements java.io.Serializable
{

	private Integer id;
	private String neirong;
	private String shijian;
	private Integer goodsId;
	private Integer userId;


	/** default constructor */
	public TPinglun()
	{
	}

	/** full constructor */
	public TPinglun(String neirong, String shijian, Integer goodsId,
			Integer userId)
	{
		this.neirong = neirong;
		this.shijian = shijian;
		this.goodsId = goodsId;
		this.userId = userId;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getNeirong()
	{
		return this.neirong;
	}

	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public Integer getGoodsId()
	{
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

}